// A trip's packing list — pure data model + pure transforms. The list
// itself is generated by AI (lib/packing-ai.ts) from the trip's own
// destinations, dates and activities; everything here is what happens to
// that list afterward — checking items off, knowing when it's gone stale.

export type PackingItem = {
  id: string;
  label: string;
  /** "Clothing", "Documents", "Shabbos", "Toiletries" — whatever the AI grouped it under. */
  category: string;
  checked: boolean;
};

export type PackingList = {
  items: PackingItem[];
  generatedAt: string;
  /** What the list was generated FOR — see tripSignature() below. Compared
   *  against the trip's current signature to know whether the list is
   *  still fresh or the trip has since changed underneath it. */
  forSignature: string;
};

export function emptyPackingList(): PackingList {
  return { items: [], generatedAt: "", forSignature: "" };
}

/**
 * A short fingerprint of what a packing list depends on — where the trip
 * goes, when, and what's actually planned. Not a hash; just a stable
 * string built from the same fields, cheap to compare. Two trips that
 * happen to collide are not a correctness problem: the worst case is an
 * unnecessary "this may be out of date" nudge, never data loss.
 */
export function tripSignature(input: { destinations: string[]; startDate?: string; endDate?: string; activityCount: number }): string {
  return [input.destinations.slice().sort().join("|"), input.startDate ?? "", input.endDate ?? "", input.activityCount].join("::");
}

/** Whether the trip has changed meaningfully since this list was made. */
export function isStale(list: PackingList, currentSignature: string): boolean {
  return list.forSignature !== currentSignature;
}

export function toggleItem(list: PackingList, id: string, checked: boolean): PackingList {
  return { ...list, items: list.items.map((i) => (i.id === id ? { ...i, checked } : i)) };
}

/** Grouped by category, in the order each category was first seen. */
export function byCategory(items: PackingItem[]): Array<{ category: string; items: PackingItem[] }> {
  const order: string[] = [];
  const groups = new Map<string, PackingItem[]>();
  for (const item of items) {
    if (!groups.has(item.category)) {
      groups.set(item.category, []);
      order.push(item.category);
    }
    groups.get(item.category)!.push(item);
  }
  return order.map((category) => ({ category, items: groups.get(category)! }));
}
